services:
  web:
    image: "authbackend:dev"
    build:
      target: development_build
      context: .
      cache_from:
        - "authbackend:dev"
        - "authbackend:latest"
        - "*"
      args:
        DJANGO_ENV: development

    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./src/.env
    depends_on:
      - db

  
  db:
    image: postgres:13.15-bullseye
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./src/.env
        
  
volumes:
    postgres_data:
      driver: local
  

  