# Generated by Django 5.0.6 on 2024-09-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, default='+977', max_length=5, null=True),
        ),
    ]
